/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef graphrpc_CONSTANTS_H
#define graphrpc_CONSTANTS_H

#include "graphrpc_types.h"

namespace GH {

class graphrpcConstants {
 public:
  graphrpcConstants();

};

extern const graphrpcConstants g_graphrpc_constants;

} // namespace

#endif
