/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "graphrpc_constants.h"

namespace GH {

const graphrpcConstants g_graphrpc_constants;

graphrpcConstants::graphrpcConstants() {
}

} // namespace

